# Default destination directory
# Files will be moved here when no destination is specified
destination: "/mnt/storage/fastlink"

# Keep original files by default
# true:  Copy files, keep originals (no symbolic links created)
# false: Move files, create symbolic links (default behavior)
keep: false